# Generated by Django 4.0 on 2021-12-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Pub_Date',
            field=models.DateField(),
        ),
    ]
