# Generated by Django 4.0 on 2021-12-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_product_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Category',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Discount',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Id',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_ImgUrl',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Name',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Price',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Quantity',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_SellingPrice',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Status',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='VendorID',
            field=models.TextField(default='', max_length=300),
        ),
    ]
