# Generated by Django 4.0 on 2021-12-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_product_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Pub_Date',
            field=models.DateField(blank=True),
        ),
    ]
