# Generated by Django 4.0 on 2021-12-16 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_product_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Pub_Date',
            field=models.DateField(blank=True, default=datetime.date(2021, 12, 16)),
        ),
    ]
