# Generated by Django 4.0 on 2021-12-16 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_product_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Pub_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
