# Generated by Django 4.0 on 2021-12-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
