# Generated by Django 4.0 on 2021-12-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_delete_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Cart',
        ),
    ]
