# Generated by Django 4.0 on 2021-12-17 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_product_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(default='', max_length=50)),
                ('Product_Quantity', models.CharField(default='1', max_length=50, verbose_name='')),
                ('Product_SellingPrice', models.CharField(default='', max_length=50)),
                ('Ordered_Date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Status', models.CharField(default='Pending', max_length=50, verbose_name='')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
