# Generated by Django 4.0 on 2021-12-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='Product',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Product_Category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Product_Description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Product_Discount',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Product_Id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Product_ImgUrl',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Product_Price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Product_Status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='Product_Quantity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='Status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
