# Generated by Django 4.0 on 2021-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_orderplaced_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendorId', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
