# Generated by Django 4.0 on 2021-12-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_vendorid_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorId',
        ),
    ]
