# Generated by Django 4.0 on 2022-01-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_orders_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='items_total',
            field=models.CharField(default='', max_length=5),
        ),
    ]
