# Generated by Django 4.0 on 2022-01-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
